name: Build ParcellesRP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Compiler ParcellesRP
        run: mvn -B clean package

      - name: Récupérer le JAR
        uses: actions/upload-artifact@v4
        with:
          name: ParcellesRP-1.0.0
          path: target/ParcellesRP-1.0.0.jar
